/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_APIROUTER_H
#define OAI_APIROUTER_H

#include <QObject>
#include <QSharedPointer>
#include <QHttpServer>

#include "OAIPetApiHandler.h"
#include "OAIStoreApiHandler.h"
#include "OAIUserApiHandler.h"


namespace OpenAPI {

class OAIApiRouter : public QObject
{
    Q_OBJECT
public:
    OAIApiRouter(QHttpServer *server);
    virtual ~OAIApiRouter();

    void setupRoutes();
    
    void setOAIPetApiHandler(QSharedPointer<OAIPetApiHandler> handler);
    void setOAIStoreApiHandler(QSharedPointer<OAIStoreApiHandler> handler);
    void setOAIUserApiHandler(QSharedPointer<OAIUserApiHandler> handler);

protected:
    // override this method to provide custom class derived from ApiHandler classes
    virtual void createApiHandlers();

private:
    QHttpServer *m_server;
    
    QSharedPointer<OAIPetApiHandler> mOAIPetApiHandler;
    QSharedPointer<OAIStoreApiHandler> mOAIStoreApiHandler;
    QSharedPointer<OAIUserApiHandler> mOAIUserApiHandler;
};


}

#endif // OAI_APIROUTER_H
