/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIPetApiHandler.h"

namespace OpenAPI {

OAIPetApiHandler::OAIPetApiHandler(){

}

OAIPetApiHandler::~OAIPetApiHandler(){

}

void OAIPetApiHandler::addPet(OAIPet body) {
    Q_UNUSED(body);
}
void OAIPetApiHandler::deletePet(qint64 pet_id, QString api_key) {
    Q_UNUSED(pet_id);
    Q_UNUSED(api_key);
}
QList<OAIPet> OAIPetApiHandler::findPetsByStatus(QList<QString> status) {
    Q_UNUSED(status);
    QList<OAIPet> res;
    return res;
}
QList<OAIPet> OAIPetApiHandler::findPetsByTags(QList<QString> tags) {
    Q_UNUSED(tags);
    QList<OAIPet> res;
    return res;
}
OAIPet OAIPetApiHandler::getPetById(qint64 pet_id) {
    Q_UNUSED(pet_id);
    OAIPet res;
    return res;
}
void OAIPetApiHandler::updatePet(OAIPet body) {
    Q_UNUSED(body);
}
void OAIPetApiHandler::updatePetWithForm(qint64 pet_id, QString name, QString status) {
    Q_UNUSED(pet_id);
    Q_UNUSED(name);
    Q_UNUSED(status);
}
OAIApiResponse OAIPetApiHandler::uploadFile(qint64 pet_id, QString additional_metadata, OAIHttpFileElement file) {
    Q_UNUSED(pet_id);
    Q_UNUSED(additional_metadata);
    Q_UNUSED(file);
    OAIApiResponse res;
    return res;
}


}
