/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIStoreApiHandler.h"

namespace OpenAPI {

OAIStoreApiHandler::OAIStoreApiHandler(){

}

OAIStoreApiHandler::~OAIStoreApiHandler(){

}

void OAIStoreApiHandler::deleteOrder(QString order_id) {
    Q_UNUSED(order_id);
}
QMap<QString, qint32> OAIStoreApiHandler::getInventory() {
    QMap<QString, qint32> res;
    return res;
}
OAIOrder OAIStoreApiHandler::getOrderById(qint64 order_id) {
    Q_UNUSED(order_id);
    OAIOrder res;
    return res;
}
OAIOrder OAIStoreApiHandler::placeOrder(OAIOrder body) {
    Q_UNUSED(body);
    OAIOrder res;
    return res;
}


}
