/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIUserApiHandler.h"

namespace OpenAPI {

OAIUserApiHandler::OAIUserApiHandler(){

}

OAIUserApiHandler::~OAIUserApiHandler(){

}

void OAIUserApiHandler::createUser(OAIUser body) {
    Q_UNUSED(body);
}
void OAIUserApiHandler::createUsersWithArrayInput(QList<OAIUser> body) {
    Q_UNUSED(body);
}
void OAIUserApiHandler::createUsersWithListInput(QList<OAIUser> body) {
    Q_UNUSED(body);
}
void OAIUserApiHandler::deleteUser(QString username) {
    Q_UNUSED(username);
}
OAIUser OAIUserApiHandler::getUserByName(QString username) {
    Q_UNUSED(username);
    OAIUser res;
    return res;
}
QString OAIUserApiHandler::loginUser(QString username, QString password) {
    Q_UNUSED(username);
    Q_UNUSED(password);
    QString res;
    return res;
}
void OAIUserApiHandler::logoutUser() {
}
void OAIUserApiHandler::updateUser(QString username, OAIUser body) {
    Q_UNUSED(username);
    Q_UNUSED(body);
}


}
